spring:
  application:
    name: product-service
  zipkin:
    base-url: http://localhost:9411/
  rabbitmq:
    host: localhost
    port: 5672
    username: admin1
    password: 123456


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    enable-self-preservation: false


server:
  port: 8772
